Summary:
Exception after about 2000 inserts
Description:
Wtih this client code and default configuration:
int max = 100000;
Random random = new Random();
for (int a = 0; a < max; a ) {
System.out.println(a);
client.insert("Table1", "k1:" random.nextInt(Integer.MAX_VALUE), "Super1:x", new byte[]
{ (byte) 1 }
, 0);
}
I get after about 2000 inserts
DEBUG [pool-1-thread-1] 2009-05-07 20:04:30,942 StorageProxy.java (line 120) insert writing key k1:1355213513 to [127.0.0.1:7000]
ERROR [ROW-MUTATION-STAGE:4] 2009-05-07 20:04:30,942 RowMutationVerbHandler.java (line 99) Error in row mutation
java.io.EOFException
at java.io.DataInputStream.readInt(Unknown Source)
at org.apache.cassandra.db.SuperColumnSerializer.fillSuperColumn(SuperColumn.java:368)
at org.apache.cassandra.db.SuperColumnSerializer.deserialize(SuperColumn.java:349)
at org.apache.cassandra.db.SuperColumnSerializer.deserialize(SuperColumn.java:314)
at org.apache.cassandra.db.ColumnFamily$ColumnFamilySerializer.deserialize(ColumnFamily.java:515)
at org.apache.cassandra.db.ColumnFamily$ColumnFamilySerializer.deserialize(ColumnFamily.java:455)
at org.apache.cassandra.db.RowMutationSerializer.defreezeTheMaps(RowMutation.java:374)
at org.apache.cassandra.db.RowMutationSerializer.deserialize(RowMutation.java:384)
at org.apache.cassandra.db.RowMutationSerializer.deserialize(RowMutation.java:337)
at org.apache.cassandra.db.RowMutationVerbHandler.doVerb(RowMutationVerbHandler.java:69)
at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:46)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Status:
RESOLVED
Priority:
Normal
Resolution:
Fixed
Affects_version:

Fix_version:
None
Component:
None
Label:
None
Environment:

Attachment number:
0
Assignee:
Jonathan Ellis
Reporter:
nk11
Create date:
07/May/09 17:13
Update date:
16/Apr/19 09:33
Resolved date:
11/May/09 14:54
