Summary:
Scanner retry behavior with RPC timeout on next() seems incorrect
Description:
I'm seeing the following behavior:
set RPC timeout to a short value
call next() for some batch of rows, big enough so the client times out before the result is returned
the HConnectionManager stuff will retry the next() call to the same server. At this point, one of two things can happen: 1) the previous next() call will still be processing, in which case you get a LeaseException, because it was removed from the map during the processing, or 2) the next() call will succeed but skip the prior batch of rows.
Status:
CLOSED
Priority:
Critical
Resolution:
Fixed
Affects_version:
0.90.7, (3)
Fix_version:
0.95.0
Component:
Client, (1)
Label:
None
Environment:

Attachment number:
0
Assignee:
Anoop Sam John
Reporter:
Todd Lipcon
Create date:
09/May/12 20:25
Update date:
19/Sep/14 20:12
Resolved date:
25/Oct/12 16:45
